spring:
  kafka:
    bootstrap-servers: localhost:29092
    partitions-count: 1
    replicas-count: 1
    topic-name:
      like-topic: like_topic
      comment-topic: comment_topic
      posts-topic: posts_topic
      views-topic: views_topic
    consumer:
      group-id: default-consumer-group

    listener:
      topics:
        views-topic:
          group-id: view-group
        like-topic:
          group-id: like-group
        comment-topic:
          group-id: comment_group
        posts-topic:
          group-id: posts_group


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
        ban_user_topic:
          name: user_ban
      post-cache:
        key-prefix: postCache
        views: views
        likes: likes
        comments: comments
        comment-end-index: 3
        feed-end-index: 500

server:
  port: 8081

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

schedule:
  banUser:
    cron: 0 0 * * * *

services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    isMocked: true
    region: Monte

