spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379
      channels:
        calculations_channel:
          name: calculations_channel
        comment_event_channel:
          name: comment_event
        comment_notification_event_channel:
          name: comment_notification_event
        post-view: post_view_channel
        post_like_event_channel:
          name: post_like_event
        post-crated: post_created_topic
      ttl:
        feed:
          post_hour: 24
          user_hour: 24
          comment_hour: 24
          user_feed_hour: 24
          post_views_counter_sec: 90
          post_likes_counter_sec: 90
          post_comments_counter_sec: 90
          comment_likes_counter_sec: 90
      retry:
        opt_lock_max_attempt: 5

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: post_feed
    template:
      default-topic: feed
    topic:
      post:
        new: posts
        update_feeds: posts_update_feeds
        view: post_views
        update_views: post_views_update
        like: likes
        update_likes: post_likes_update
        comment: comments
        update_comments: post_comments_update
        like_post_comment: like_comment
        update_post_comments_likes: post_comment_likes_update
      user:
        feed_update: feed_update
        ban: user_ban

server:
  port: 8081

post:
  pool-size: 10
  publisher:
    batch-size: 100
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  spelling-corrector:
    batch-size: 10
    scheduler:
      cron: "0 0 0 * * *" # каждый день в 00:00:00
    retry:
      delay: 2000
      multiplier: 2
    client:
      textgears:
        correct-endpoint: https://api.textgears.com/correct
        lang-detector-endpoint: https://api.textgears.com/detect
        auth-token: secret-key
      yandex:
        url: https://speller.yandex.net/services/spellservice.json/checkText
  images:
    max-to-upload: 10
    max-size: 5242880
    bucket:
      name-prefix: posts/post_

client:
  s3:
    minio:
      url: http://127.0.0.1:9000
      username: user
      password: password
      bucketName: corpbucket

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

moderation:
  sublist-size: 10
  thread-pool-size: 5

quartz:
  job:
    interval-seconds: 30000000

app:
  post:
    feed:
      update:
        followers_partitions_limit: 10
        view_counter_partition_limit: 10
        like_counter_partition_limit: 10
        comment_counter_partition_limit: 10
        post_comment_likes_partition_limit: 10
        users_feed_update_partition_limit: 5
      scheduler:
        cron:
          post_view_counter_collector: "0 0/1 * 1/1 * ?" # every minute
          post_like_counter_collector: "0 0/1 * 1/1 * ?" # every minute
          post_comment_counter_collector: "0 0/1 * 1/1 * ?" # every minute
          post_comment_like_counter_collector: "0 0/1 * 1/1 * ?" # every minute
    cache:
      hash_tag:
        prefix:
          post_id: "hash_tag/post_id:"
        number_of_top_in_cache: 10
      news_feed:
        prefix:
          post_id: "post_id:"
          user_id: "user_id:"
          comment_id: "comment_id:"
          feed_prefix: "feed/"
          post_comments_ids_set: "comment/"
        postfix:
          views: "/views"
          likes: "/likes"
          comments: "/comments"
        user_feed_size: 10
        user_feed_size_zset_index: -11  # limit is 10 = (10 + 1) * -1
        number_of_comments_limit: 3
        max_index_for_get_comments_in_post_comments_set: 2
        number_of_comment_ids_in_post_comments_set: -11  # limit is 10 = (10 + 1) * -1
  async-config:
    post-cache-service:
      core_pool_size: 10
      max_pool_size: 20
      queue_capacity: 1000
      thread_mane_prefix: PostCacheProcessExecutor-Async-
    users_feed_update:
      core_pool_size: 10
      max_pool_size: 20
      queue_capacity: 1000
      thread_mane_prefix: UsersFeedUpdateExecutor-Async-
    redis-publisher-async-pool:
      core_pool_size: 10
      max_pool_size: 10

springdoc:
  api-docs:
    path: /api-docs

redis:
  banner:
    schedule: "0 0 0 * * ?"