spring:
  mvc:
    servlet:
      path: /api/v1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        like_event_channel: like_event_channel
        calculations_channel:
          name: calculations_channel
        comment: comment_channel
      feed-cache:
        batch_size: 20
        max_feed_size: 500
        key: "feed:"
        number_of_users_on_page: 3
      post-cache:
        comments-in-post: 3
      time_to_live:
        post: 86400
        user: 86400
      redisson_client:
        name_version: version
        key_for_version: versionedKey
        start_num_for_version: 1
        lock_cache_post: "lock:cachePost:"

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      deserializer-trusted-packages: "java.util,java.lang,faang.school.postservice.dto.event"
      groupId: consumer-group-one
    topic:
      posts: posts
      likes: likes
      comments: comments
      post_views: post-views
      feed_heater: feed-heater

server:
  port: 8081

logging:
  level:
    root: info

news-feed:
  heater:
    threads: 4

post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

