spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  kafka:
    port: 9092
    host: localhost
    group_id: news_feed
    topics_names: posts

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        comment-notification-channel: comment-topic
        ad-bought-channel: ad-bought-topic
        comment-channel: comment-topic
        ban-channel: user-ban


server:
  port: 8081

scheduling:
  cron: "0 0 12 * * *"

spelling:
  key: c2b61bcbe1msh7baed25073c44a3p111bcfjsn7841c9808baa
  endpoint: https://jspell-checker.p.rapidapi.com/check
  content: application/json
  host: jspell-checker.p.rapidapi.com

logging:
  level:
    root: info

moderation-scheduler:
  cron: 0 0 * * * *
  post-batch-size: 20
  dictionary-path: src\main\resources\dictionary\moderator.json

services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: post-bucket

cache:
  author:
    ttl: 24
  post:
    ttl: 24
  news_feed:
    prefix_name: News_Feed
    max_posts_amount: 500
    page_size: 20

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080