spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

  cloud:
    openfeign:
      client:
        config:
          user-service:
            url: http://localhost:8080/api/v1/
            connect-timeout: 5000
            read-timeout: 5000
          project-service:
            url: http://localhost:8082/api/v1/
            connect-timeout: 5000
            read-timeout: 5000
          payment-service:
            url: http://localhost:9080/api/
            connect-timeout: 5000
            read-timeout: 5000

server:
  port: 8081

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080
