spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      postTtl: 1 # in days
      defaultTtl: 1 # in days
      authorTtl: 1 # in days
      maxPostCountInFeed: 500
      commentTtl: 1 # in days
      redissonAddress: redis://localhost:6379
      commentsSize: 3
      channels:
        calculationsChannel:
          name: calculations_channel
        commentChannel:
          name: comment_channel
        likePostChannel:
          name: like_post_channel
        newCommentChannel:
          name: new_comment_channel
        postViewChannel:
          name: post_view_channel
        userBanChannel:
          name: user_ban_channel
    kafka:
      consumerConfig:
        bootstrapServersConfig: localhost:9092
        groupId: 1
        autoOffsetReset: "earliest"
        enableAutoCommit: false
        interval: 1000
        maxPollRecords: 100
        sessionTimeout: 15000
        trustedPackages: "*"
      producerConfig:
        bootstrapServersConfig: localhost:9092
        acks: "all"
        retries: 5
        idempotence: true
      topics:
        commentLikeTopic:
          name: comment_likes
          numPartitions: 5
          replicationFactor: 1
        postLikeTopic:
          name: post_likes
          numPartitions: 5
          replicationFactor: 1
        postCreatedTopic:
          name: postsTopic
          numPartitions: 5
          replicationFactor: 1
        commentCreatedTopic:
          name: comments
          numPartitions: 5
          replicationFactor: 1

server:
  port: 8081

logging:
  level:
    root: info

post:
  executor:
    threads:
      count: 5
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  moderation:
    scheduler:
      cron: "0 0 * * * ?" # every day at 00:00
    dictionary:
      file-path: "src/main/resources/moderation/dictionary.txt"
    sublist:
      length: 10
  author-banner:
    schedule:
      cron: "0 0/10 * * * ?" # event 10 minutes
    unverified-posts-limit: 5
    unverified-posts-days: 30

user-service:
  host: localhost
  port: 8080
  requiredHeaders: x-user-id
project-service:
  host: localhost
  port: 8082
  requiredHeaders: x-user-id
payment-service:
  host: localhost
  port: 9080
  requiredHeaders: x-user-id

moderate:
  comments:
    initialDelay: 5000
    fixedDelay: 3600000

dictionary:
  offensive:
    initial: "dictionary/offensive-words.yaml"
    remote:
      url: https://raw.githubusercontent.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/refs/heads/master
      scheduler:
        cron: "0 0 0/24 * * *" # every 24 hours
    update:
      retry:
        maxAttempts: 2
        maxDelay: 1000
services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    connectionTimeout: 50_000
    socketTimeout: 50_000

executor:
  capacity: 10
  corePoolSize: 1
  maximumPoolSize: 10
  keepAliveTime: 60

aws:
  java:
    v1:
      disableDeprecationAnnouncement: true
