spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
        like-event-topic: likeEventTopic
        comment: comment_channel

  task:
    scheduling:
      pool:
        size: 5

server:
  port: 8081

logging:
  level:
    root: info
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG

s3:
  endpoint: http://localhost:9000
  accessKey: user
  secretKey: password
  bucketName: corpbucket
  isMocked: false
user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

api:
  content-analysis-service:
    base-url: https://api.sightengine.com
    key: 1300876459
    secret: 3aFptFRLejnfzx9kYkBhnSasJKymfQao

resilience4j:
  circuitbreaker:
    instances:
      sightengine-api-circuit-breaker:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      sightengine-api-retry:
        max-attempts: 5
        wait-duration: 200ms
        exponential-backoff-multiplier: 2.0

thread-pool:
  verification-content-pool:
    num-of-thread: 5
    num-of-chunk: 10

schedule:
  verify-posts:
    cron: "0 0 3 * * ?"

moderation:
  dictionary:
    path: src/main/resources/dictionary.json
    text-split-regex: "[^\\p{L}\\p{N}]+"
  targets:
    SEXUAL: 0.7
    DISCRIMINATORY: 0.7
    INSULTING: 0.7
    VIOLENT: 0.7
    TOXIC: 0.7

daily:
  cron:
   comment-moderation: 0 0 10 * * *