spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        like: like_channel
        comment: comment_channel
        calculations_channel:
          name: calculations_channel

    kafka:
      topics:
        comments:
          name: comment-created-events-topic
          partitions: 3
          replicas: 3
          configs:
            min.insync.replicas: 2
        likes:
          name: likes-events-topic
          partitions: 2
          replicas: 2
          configs:
            min.insync.replicas: 2
  kafka:
    producer:
      bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    admin:
      properties:
        retries: 5
        retry.backoff.ms: 500
        metadata.fetch.timeout.ms: 15000

server:
  port: 8081

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080
