spring:

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  crontab:
    checkPostsGrammar: "15 54 19 * * *"
  task:
     execution:
        pool:
          core-size: 5
          max-size: 10
          queue-capacity: 25
        thread-name-prefix: checkPostsGrammarExecutor


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
        userBanChannel:
          name: user_ban_channel

server:
  port: 8081

logging:
  level:
    root: info

post:
  author-banner:
    schedule:
      cron: "0 0 0 * * *"
    unverified-posts-limit: 5

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    max-image-size-mb: 5
    max-images-count-for-post: 10
    max-width-horizontal-image: 1080
    max-height-horizontal-image: 566
    max-side-square-image: 1080
  text-gears:
    url: https://textgears-textgears-v1.p.rapidapi.com/correct
    header-1: x-rapidapi-key
    api-key: 52b8fb4f25msh122fa7902a41e9bp1105cejsn54289f3bb474
    header-2: x-rapidapi-host
    value-host: textgears-textgears-v1.p.rapidapi.com
    header-3: Content-Type
    method: POST
    body: text=
