spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

server:
  port: 8081

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

springdoc:
  api-docs:
    path: /v3/post-service-api-docs
  swagger-ui:
    path: /post-service-ui.html

  services:
    s3:
      endpoint: http://127.0.0.1:9000
      accessKey: user
      secretKey: password
      bucketName: post-service-bucket
      region: US_EAST_1

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB

  resources:
    file:
      max-file-size: 5242880
    image:
      max-width-horizontal: 1080
      max-height-horizontal: 566
      max-size-square: 1080
      supported-image-types: "image/png,image/jpeg,image/jpg"
    cleanup:
      scheduler:
        cron: "0 0 2 * * ?" # каждый день в 2 часа ночи
      retention-period: 1M # настройка периода: M - месяц, D - день