spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        like_channel: like_channel
        calculations_channel:
          name: calculations_channel

server:
  port: 8081

logging:
  level:
    root: debug

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

moderation:
  batch-size: 50
  cron: 0 0 0 * * *
  zone: Europe/Moscow
  thread-pool-size: 1

api:
  version: "/api/v1"
