spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        comment-channel: comment-topic
        ban-channel: user-ban


server:
  port: 8081

logging:
  level:
    root: info

moderation-scheduler:
  cron: 0 0 * * * *
  post-batch-size: 20
  dictionary-path: src\main\resources\dictionary\moderator.json

services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: post-bucket

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080