spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      comment-max-size: 3
      channels:
        like: like_channel
        comment: comment_channel
        calculations_channel:
          name: calculations_channel

    kafka:
      topics:
        comments:
          name: comment-created-events-topic
          partitions: 3
          replicas: 3
          configs:
            min-insync-replicas: 2

  kafka:
    producer:
      bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    consumer:
      bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
      group-id: comment-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      concurrency: 3
      enable-auto-commit: false
      ack-mode: MANUAL_IMMEDIATE
      properties:
        allow.auto.create.topics: false
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: faang.school.postservice.dto.CommentEvent
    admin:
      properties:
        retries: 5

server:
  port: 8081

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080
